### ISSUE TITLE
Build private web page of all results with Jupyter book 

### ISSUE THREAD

**Issue by sanjaynagi** [sanjaynagi/AmpSeeker#16]
@ChabbyTMD @eddUG 

I was having a think, and I think it should be possible to use Jupyter-book within snakemake to build a private web-site, which contains all of the results of the workflow for each users analysis. 

This would be really cool, imagine that you wouldn't even need to look in the results folder, one could simply open the webpage and explore all the results that way. If we make the analyses in papermill/Jupyter-notebooks, this shouldn't be too complicated! 

(Ill explain in our next meeting, but jupyter-book can basically take as input a load of jupyter notebooks and build a website from it).

**Comment by ChabbyTMD** [comment]
This sounds awesome Sanjay... That would greatly improve the user friendliness of the work flow and decrease friction in deriving insight from the output. 

Who knows we might even design a GUI front end to dynamically handle inputs (reads, reference, snp targets etc.) to feed into the workflow at the backend and present the results as the jupyter derived webpage as you suggested.

**Comment by sanjaynagi** [comment]
Here is an example of a jupyter book associated with a snakemake workflow - https://github.com/sanjaynagi/rna-seq-pop/tree/master/docs/rna-seq-pop-book

and a snakemake workflow which actually builds the book automatically, which is what we would ultimately want to do - https://github.com/anopheles-genomic-surveillance/selection-atlas

**Comment by sanjaynagi** [comment]
Although the results web book still needs further work, Im going to close this issue and assume we will continue to improve the book. Closed with #31 . Thanks @ChabbyTMD
