### ISSUE TITLE
Search the literature for sensible QC options in Amplicon sequencing

### ISSUE THREAD

**Issue by sanjaynagi** [sanjaynagi/AmpSeeker#21]
- need to ensure we are implementing some sensible QC steps, I dont quite know what these would look like atm.

**Comment by ChabbyTMD** [comment]
Possible QC tool: https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-016-1069-7

**Comment by sanjaynagi** [comment]
Suggestion from @eddUG to use qualimap on the BAM files, aswell as just the current `samtools flagstat` which is pretty basic.

**Comment by sanjaynagi** [comment]
Think this is pretty much resolved by #27 #26 . Now we just need QC for Variant calling. Will make a new issue.
