### ISSUE TITLE
set standards for bed file, and accompanying tsv file 

### ISSUE THREAD

**Issue by sanjaynagi** [sanjaynagi/AmpSeeker#8]
What columns are required?

**Comment by sanjaynagi** [comment]
Should we just use a bed? with extra columns?

**Comment by sanjaynagi** [comment]
and for metadata, what columns should we need? 

make example files.

**Comment by sanjaynagi** [comment]
chromosome / start / stop / name (aa_change) / gene

**Comment by sanjaynagi** [comment]
We now require 

bed file - chromosome / start / stop / name (could be aa_change) / type
metadata - sampleID / taxon / country / location / latitude / longitude

**Comment by sanjaynagi** [comment]
Closing for now

**Comment by ChabbyTMD** [comment]
Hi Sanjay, could you please send me the AgamDao.bed file you used in the config directory.

**Comment by sanjaynagi** [comment]
Hey Trevor. I can’t send you it as I’m on vacation now until next Tuesday. But the bed file has 5 columns with no header - chrom, start, stop, snp_name, snp_type.Currently snp name and type are not being used but will need to be present SanjSent from my iPhoneOn 18 May 2023, at 08:13, Trevor Mugoya ***@***.***> wrote:﻿
Hi Sanjay, could you please send me the AgamDao.bed file you used in the config directory.
